"""run of show script segments

Revision ID: 07b273efad05
Revises: 62aa7603ff63
Create Date: 2026-09-14 00:30:45.141503
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '07b273efad05'
down_revision = '62aa7603ff63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script_segments', sa.Column('segment_type', sa.String(length=16), server_default='topic', nullable=False))
    op.add_column('script_segments', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('script_segments', sa.Column('start_minute', sa.Integer(), nullable=True))
    op.add_column('script_segments', sa.Column('planned_minutes', sa.Integer(), nullable=True))
    op.add_column('script_segments', sa.Column('transition_in', sa.Text(), nullable=True))
    op.add_column('script_segments', sa.Column('host_script', sa.Text(), nullable=True))
    op.add_column('script_segments', sa.Column('deeper_questions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('script_segments', sa.Column('flagged_unsourced', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('scripts', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.alter_column('scripts', 'model_version',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)
    # Autogenerate does not detect CHECK constraints on existing tables.
    op.create_check_constraint(
        "ck_segment_type",
        "script_segments",
        "segment_type IN ('opening','topic','bonus','closing')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_segment_type", "script_segments", type_="check")
    op.alter_column('scripts', 'model_version',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('scripts', 'duration_minutes')
    op.drop_column('script_segments', 'flagged_unsourced')
    op.drop_column('script_segments', 'deeper_questions')
    op.drop_column('script_segments', 'host_script')
    op.drop_column('script_segments', 'transition_in')
    op.drop_column('script_segments', 'planned_minutes')
    op.drop_column('script_segments', 'start_minute')
    op.drop_column('script_segments', 'title')
    op.drop_column('script_segments', 'segment_type')
    # ### end Alembic commands ###
