"""provider pacing

Revision ID: 29e6f7bd1bb2
Revises: 8fcb47db97a0
Create Date: 2026-09-10 14:36:06.971267
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '29e6f7bd1bb2'
down_revision = '8fcb47db97a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_pacing',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('last_call_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_pacing')
    # ### end Alembic commands ###
