"""dossier cluster fk set null

Revision ID: 62aa7603ff63
Revises: 69e3d5d2233f
Create Date: 2026-09-10 14:56:20.109779
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '62aa7603ff63'
down_revision = '69e3d5d2233f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dossier_items_cluster_id_fkey'), 'dossier_items', type_='foreignkey')
    op.create_foreign_key(None, 'dossier_items', 'claim_clusters', ['cluster_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dossier_items', type_='foreignkey')
    op.create_foreign_key(op.f('dossier_items_cluster_id_fkey'), 'dossier_items', 'claim_clusters', ['cluster_id'], ['id'])
    # ### end Alembic commands ###
