"""initial schema

Revision ID: 64aa8633b77e
Revises: 
Create Date: 2026-09-10 01:29:23.251711
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '64aa8633b77e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # pgvector must exist before any Vector column is created, so that a fresh
    # database migrates without manual setup.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=True),
    sa.Column('employer', sa.String(length=512), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type IN ('person','company','topic')", name='ck_entity_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entities_type_name', 'entities', ['type', 'name'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=512), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blob_ref', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','fetched','parsed','failed')", name='ck_source_status'),
    sa.CheckConstraint("type IN ('web_article','youtube','pdf','profile','user_pasted')", name='ck_source_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url', name='uq_sources_canonical_url'),
    sa.UniqueConstraint('checksum', name='uq_sources_checksum')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('speaker', sa.String(length=255), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.CheckConstraint('(start_offset IS NOT NULL AND end_offset IS NOT NULL) OR (start_ms IS NOT NULL AND end_ms IS NOT NULL)', name='ck_chunk_has_position'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'ordinal', name='uq_chunk_source_ordinal')
    )
    op.create_index(op.f('ix_chunks_source_id'), 'chunks', ['source_id'], unique=False)
    op.create_table('claim_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_entity_id', sa.UUID(), nullable=False),
    sa.Column('canonical_text', sa.Text(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_clusters_subject_entity_id'), 'claim_clusters', ['subject_entity_id'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('guest_entity_id', sa.UUID(), nullable=True),
    sa.Column('topic_entity_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('guest_name', sa.String(length=512), nullable=False),
    sa.Column('disambiguator', sa.String(length=1024), nullable=False),
    sa.Column('coverage_mode', sa.String(length=16), nullable=True),
    sa.Column('coverage_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('identifying','ingesting','dossier_ready','script_ready')", name='ck_episode_status'),
    sa.ForeignKeyConstraint(['guest_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['topic_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_user_id'), 'episodes', ['user_id'], unique=False)
    op.create_table('usage_counters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', 'kind', name='uq_usage_user_day_kind')
    )
    op.create_table('citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.CheckConstraint("target_type IN ('dossier_item','script_segment')", name='ck_citation_target'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_citations_target', 'citations', ['target_type', 'target_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('subject_entity_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('claim_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=False),
    sa.Column('span_end', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('biographical','opinion','fact','anecdote','prediction')", name='ck_claim_kind'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['claim_clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'text_hash', 'extractor_version', name='uq_claim_chunk_text_version')
    )
    op.create_index(op.f('ix_claims_chunk_id'), 'claims', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_claims_cluster_id'), 'claims', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_claims_subject_entity_id'), 'claims', ['subject_entity_id'], unique=False)
    op.create_index('ix_claims_subject_kind', 'claims', ['subject_entity_id', 'kind'], unique=False)
    op.create_table('dossier_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('item_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('flagged_unsourced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['claim_clusters.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dossier_episode_section', 'dossier_items', ['episode_id', 'section', 'ordinal'], unique=False)
    op.create_index(op.f('ix_dossier_items_episode_id'), 'dossier_items', ['episode_id'], unique=False)
    op.create_table('episode_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('added_by', sa.String(length=16), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'source_id', name='uq_episode_source')
    )
    op.create_index(op.f('ix_episode_sources_episode_id'), 'episode_sources', ['episode_id'], unique=False)
    op.create_index(op.f('ix_episode_sources_source_id'), 'episode_sources', ['source_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('queued','running','done','failed','dead')", name='ck_job_state'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_job_idempotency')
    )
    op.create_index('ix_jobs_dequeue', 'jobs', ['state', 'next_attempt_at'], unique=False)
    op.create_index('ix_jobs_episode', 'jobs', ['episode_id', 'state'], unique=False)
    op.create_index('ix_jobs_user_running', 'jobs', ['user_id', 'state'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('style_preset', sa.String(length=32), nullable=False),
    sa.Column('voice_sample_ref', sa.Text(), nullable=True),
    sa.Column('voice_descriptors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_episode_id'), 'scripts', ['episode_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'ordinal', name='uq_topic_episode_ordinal')
    )
    op.create_index(op.f('ix_topics_episode_id'), 'topics', ['episode_id'], unique=False)
    op.create_table('script_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('expected_direction', sa.Text(), nullable=True),
    sa.Column('followups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claim_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_id', 'ordinal', name='uq_segment_script_ordinal')
    )
    op.create_index(op.f('ix_script_segments_script_id'), 'script_segments', ['script_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_script_segments_script_id'), table_name='script_segments')
    op.drop_table('script_segments')
    op.drop_index(op.f('ix_topics_episode_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_scripts_episode_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index('ix_jobs_user_running', table_name='jobs')
    op.drop_index('ix_jobs_episode', table_name='jobs')
    op.drop_index('ix_jobs_dequeue', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_episode_sources_source_id'), table_name='episode_sources')
    op.drop_index(op.f('ix_episode_sources_episode_id'), table_name='episode_sources')
    op.drop_table('episode_sources')
    op.drop_index(op.f('ix_dossier_items_episode_id'), table_name='dossier_items')
    op.drop_index('ix_dossier_episode_section', table_name='dossier_items')
    op.drop_table('dossier_items')
    op.drop_index('ix_claims_subject_kind', table_name='claims')
    op.drop_index(op.f('ix_claims_subject_entity_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_cluster_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_chunk_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_citations_target', table_name='citations')
    op.drop_table('citations')
    op.drop_table('usage_counters')
    op.drop_index(op.f('ix_episodes_user_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_claim_clusters_subject_entity_id'), table_name='claim_clusters')
    op.drop_table('claim_clusters')
    op.drop_index(op.f('ix_chunks_source_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_index('ix_entities_type_name', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
