"""widen extractor_version

Revision ID: 69e3d5d2233f
Revises: 29e6f7bd1bb2
Create Date: 2026-09-10 14:44:52.185190
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '69e3d5d2233f'
down_revision = '29e6f7bd1bb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'extractor_version',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'extractor_version',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
