"""script revisions

Revision ID: 7074f3966790
Revises: 07b273efad05
Create Date: 2026-09-15 18:25:02.816894
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '7074f3966790'
down_revision = '07b273efad05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('parent_script_id', sa.UUID(), nullable=True))
    op.add_column('scripts', sa.Column('feedback', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'scripts', 'scripts', ['parent_script_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scripts', type_='foreignkey')
    op.drop_column('scripts', 'feedback')
    op.drop_column('scripts', 'parent_script_id')
    # ### end Alembic commands ###
