"""provider budgets

Revision ID: 8fcb47db97a0
Revises: 64aa8633b77e
Create Date: 2026-09-10 13:56:58.522327
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '8fcb47db97a0'
down_revision = '64aa8633b77e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'period', name='uq_budget_provider_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_budgets')
    # ### end Alembic commands ###
