"""source subjects

Revision ID: b58f84ebe966
Revises: 7074f3966790
Create Date: 2026-09-15 18:57:32.505952
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = 'b58f84ebe966'
down_revision = '7074f3966790'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode_sources', sa.Column('subject_entity_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'episode_sources', 'entities', ['subject_entity_id'], ['id'], ondelete='SET NULL')
    # Backfill: label existing attachments. First from the subject each fetch or
    # extract job recorded, then by inference from whose claims a source produced.
    # Anything left NULL is treated as the guest.
    op.execute(sa.text("""
        UPDATE episode_sources es
        SET subject_entity_id = CAST(j.payload->>'subject_entity_id' AS uuid)
        FROM jobs j
        WHERE j.episode_id = es.episode_id
          AND j.kind IN ('fetch_source', 'extract_claims')
          AND j.payload->>'source_id' = CAST(es.source_id AS text)
          AND j.payload->>'subject_entity_id' IS NOT NULL
    """))
    op.execute(sa.text("""
        UPDATE episode_sources es
        SET subject_entity_id = e.topic_entity_id
        FROM episodes e
        WHERE es.episode_id = e.id
          AND es.subject_entity_id IS NULL
          AND e.topic_entity_id IS NOT NULL
          AND EXISTS (SELECT 1 FROM claims c JOIN chunks ch ON ch.id = c.chunk_id
                      WHERE ch.source_id = es.source_id AND c.subject_entity_id = e.topic_entity_id)
          AND NOT EXISTS (SELECT 1 FROM claims c JOIN chunks ch ON ch.id = c.chunk_id
                          WHERE ch.source_id = es.source_id AND c.subject_entity_id = e.guest_entity_id)
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'episode_sources', type_='foreignkey')
    op.drop_column('episode_sources', 'subject_entity_id')
    # ### end Alembic commands ###
